#!/bin/bash
# Credits: @mrismanaziz
# Copyright (C) 2022 Pyro-ManUserbot
#
# This file is a part of < https://github.com/ji1nonly/PYRODARK-USERBOT/ >
# PLease read the GNU Affero General Public License in
# <https://www.github.com/ji1nonly/PYRODARK-USERBOT/blob/main/LICENSE/>.
#
# t.me/poconguserbot & t.me/lyoc0de

python3 -m ProjectPyrodark
