#!/bin/bash
# Credits: @mrismanaziz
# Copyright (C) 2022 Pyro-ManUserbot
#
# This file is a part of < https://github.com/aldiboyy/PYROALCI-USERBOT/ >
# PLease read the GNU Affero General Public License in
# <https://www.github.com/aldiboyy/PYROALCI-USERBOT/blob/main/LICENSE/>.
#
# t.me/poconguserbot & t.me/lyoc0de

python3 -m ProjectPyrodark
