#!/bin/bash
# Credits: @mrismanaziz
# Copyright (C) 2022 Pyro-ManUserbot
#
# This file is a part of < https://github.com/xiayow/NATH-USERBOT/ >
# PLease read the GNU Affero General Public License in
# <https://www.github.com/xiayow/NATH-USERBOT/blob/main/LICENSE/>.
#
# t.me/nathsupport & t.me/nathaellxx

python3 -m Projectpyronath
